# 3.1一維陣列

In [1]:
import numpy as np #載入numpy package

In [4]:
np.version

<module 'numpy.version' from 'C:\\Anaconda3\\lib\\site-packages\\numpy\\version.py'>

In [5]:
a = np.array([1 , 4 , 5 , 8 , 7], dtype = float) #dtype指定元素的資料類別

In [6]:
a

array([ 1.,  4.,  5.,  8.,  7.])

In [7]:
type(a) #想知道a的資料類別

numpy.ndarray

In [8]:
a.dtype #想要知道array a中元素的資料類別

dtype('float64')

In [9]:
a.ndim #想知道array a是幾維的陣列

1

In [11]:
len(a); a.size #想知道array a的長度(即元素個數)

5

當然我們也可以建構一個複數陣列。

In [12]:
np.array([-2+3j , 4-5j , 6.7+10.5j], dtype = complex)

array([-2.0 +3.j ,  4.0 -5.j ,  6.7+10.5j])

也可以建構一個字串陣列。

In [13]:
np.array(["pamela" , "Monica" , "Violana"], dtype = str)

array(['pamela', 'Monica', 'Violana'], 
      dtype='<U7')

In [15]:
np.arange(5 , dtype = int) #建構一個 0~5 的整數數列

array([0, 1, 2, 3, 4])

In [16]:
np.arange(start=1, stop=10, step=2, dtype = int) #建構一個奇數的整數陣列

array([1, 3, 5, 7, 9])

# 練習：

In [17]:
d = np.array([11, 22, 33, 44])

In [18]:
d

array([11, 22, 33, 44])

In [20]:
d[1] = 55 #輕鬆改變一個陣列的內容

In [21]:
d

array([11, 55, 33, 44])

In [22]:
d[[0, 1, 3]] = 101

In [23]:
d

array([101, 101,  33, 101])

In [24]:
index=[0, 1, 3]
d[index] = 202

In [25]:
d

array([202, 202,  33, 202])

使用np.concatenate()將兩個陣列左右合為一個陣列：

In [26]:
a = np.array([1, 2])
b = np.array([3, 4, 5])
c = np.array([6, 7, 8, 9])

In [27]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5])

In [28]:
np.concatenate((a, b, c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.concatenate((a, [99])) #在 a 陣列最後加入 99 這個數

array([ 1,  2, 99])

In [30]:
np.concatenate((a, [88, 99])) #在 a 陣列最後加入 88 和 99 這兩個數

array([ 1,  2, 88, 99])

# NumPy提供常見的數學函數，如：
   abs(x), sqrt(x), log(x), log10(x), log2(x), exp(x), sin(x), cos(x), tan(x), len(x), mean(x), median(x), var(x), std(x)

In [31]:
np.sign(np.array([-2.5, 0, 3.4]))   

array([-1.,  0.,  1.])

In [34]:
np.log(np.array([1, 10, 100]))

array([ 0.        ,  2.30258509,  4.60517019])

In [37]:
np.log10(np.array([1, 10, 100]))

array([ 0.,  1.,  2.])

In [38]:
np.log2(np.array([1, 2, 4, 8]))

array([ 0.,  1.,  2.,  3.])

In [39]:
x = np.arange(5) * np.pi/4

In [40]:
x

array([ 0.        ,  0.78539816,  1.57079633,  2.35619449,  3.14159265])

In [41]:
sx = np.sin(x)

In [42]:
sx

array([  0.00000000e+00,   7.07106781e-01,   1.00000000e+00,
         7.07106781e-01,   1.22464680e-16])

In [43]:
np.math.factorial(4)

24

In [44]:
x = np.array([1.123, 1.5, 1.999], float)

In [45]:
x

array([ 1.123,  1.5  ,  1.999])